using System.Diagnostics;
using Core;

namespace Engine.Nnue;

/// <summary>
/// Curated, fixed configuration for the continuous trainer. The only external knob is cores.
/// </summary>
public sealed class LoopConfig
{
    public int Cores;
    public int Depth = 6;
    public int RandomPlies = 10;
    public int H = 128;
    public float Lr = 0.002f;
    public float Lambda = 0.9f;
    public int Window = 1_500_000;         // sliding replay-buffer size (positions)
    public int ReusePerNewSample = 4;      // samples drawn from the replay buffer per fresh position
                                           // (bounded reuse avoids overfitting early buckets as the buffer grows)
    public int MeasureEvery = 10;          // measure vs the hand-crafted anchor every N generations
    public int MeasureGames = 40;          // enough games that the switch decision isn't fooled by noise (20 was ±11%)
    public double SwitchThreshold = 0.55;  // hand-crafted → net-teacher once the net clearly leads the anchor
    public double GateThreshold = 0.53;    // net-teacher: promote a candidate only if it beats the current best head-to-head
    public int MaxIterations = 0;          // 0 = run until cancelled
    public int GamesPerIter => 32 * Math.Max(1, Cores);   // ~80s of generation at typical core counts
}

/// <summary>
/// Per-iteration summary pushed to an observer (console now, Spectre dashboard later).
/// </summary>
public readonly record struct IterReport(
    int Generation, int BufferPositions, bool NetTeacher,
    double GenSec, double GamesPerSec, double TrainSec, double Mse, double? Score);

/// <summary>
/// Observer hooks so the loop stays headless and a UI can subscribe.
/// </summary>
public sealed class LoopEvents
{
    public Action<string>? Stage;             // "generating" | "training" | "measuring" | "saving"
    public Action<int, int>? Progress;        // (done, total) within the current stage
    public Action<IterReport>? Iteration;     // one generation finished
    public Action<string>? Info;              // misc messages
}

/// <summary>
/// The fire-and-forget trainer. One persistent correction net is generated-against, fed into a sliding
/// replay buffer, and warm-started each iteration, with no cold-start retrains. Runs until cancelled; it
/// resumes from the last checkpoint WITH its replay buffer (persisted to disk) so a restart no longer wipes
/// the net's training data. The teacher is the hand-crafted eval until the net surpasses it; thereafter
/// self-play is generated by the BEST net so far (net-vs-net gating), so a drifting candidate can't poison
/// the data or regress what we ship. The released net only ever ratchets up.
///
/// Each iteration runs five stages: generate self-play data, append it to the replay buffer, warm-start
/// train the candidate, checkpoint, and periodically measure-and-gate the candidate against the best net.
/// </summary>
public sealed class ContinuousLoop
{
    private readonly LoopConfig cfg;
    private readonly LoopEvents events;
    private readonly string netDir;
    private readonly NnueTrainer trainer;
    private readonly List<Example> buffer = [];    // pre-extracted features for training
    private readonly List<Sample> rawBuffer = [];  // the raw positions behind them, for on-disk persistence
    private int generation;
    private bool netTeacher;
    private NnueNetwork bestNet;     // frozen best: the self-play teacher and the released checkpoint
    private double bestScore;        // best net's score vs the hand-crafted anchor (for display)

    /// <summary>
    /// Sets up the loop, resuming from the last on-disk checkpoint and replay buffer if one exists, otherwise starting fresh from a random net.
    /// </summary>
    public ContinuousLoop(LoopConfig cfg, LoopEvents events)
    {
        this.cfg = cfg;
        this.events = events;
        netDir = Path.Combine(Paths.Models, "train");
        Directory.CreateDirectory(netDir);

        var net = TryResume(out generation, out netTeacher, out bestScore) ?? NnueNetwork.CreateRandom(cfg.H, 32, Trainer.K, seed: 7);
        trainer = new NnueTrainer(net, cfg.Lr);
        bestNet = TryLoad(BestPath) ?? net.Clone();

        LoadCorpus();   // restore the replay buffer so a restart doesn't relearn from an empty buffer

        events.Info?.Invoke(generation == 0
            ? $"starting fresh (H={cfg.H})"
            : $"resumed from generation {generation}, buffer {buffer.Count:n0} positions, teacher={(netTeacher ? "net" : "hand-crafted")}");
    }

    /// <summary>
    /// Runs the generate/buffer/train/checkpoint/measure cycle until cancelled (or <see cref="LoopConfig.MaxIterations"/> is reached), checkpointing as it goes so it is always safe to stop.
    /// </summary>
    public void Run(CancellationToken ct)
    {
        int baseSeed = 1;
        int startGen = generation;
        while (!ct.IsCancellationRequested && (cfg.MaxIterations <= 0 || generation - startGen < cfg.MaxIterations))
        {
            generation++;

            // 1. GENERATE (parallel self-play; teacher is the BEST net once bootstrapped, else hand-crafted)
            events.Stage?.Invoke("generating");
            var genClock = Stopwatch.StartNew();
            int[] done = [0];
            var samples = DataGen.GenerateSamples(cfg.GamesPerIter, cfg.Depth, cfg.RandomPlies,
                baseSeed + generation * 100003, netTeacher ? bestNet : null, cfg.Cores, ct,
                () => events.Progress?.Invoke(System.Threading.Interlocked.Increment(ref done[0]), cfg.GamesPerIter));
            genClock.Stop();
            if (ct.IsCancellationRequested) break;

            // 2. BUFFER (append features + raw positions in lockstep, slide the window on both)
            var fresh = Trainer.BuildExamples(samples, cfg.Lambda);
            buffer.AddRange(fresh);
            rawBuffer.AddRange(samples);
            if (buffer.Count > cfg.Window)
            {
                int drop = buffer.Count - cfg.Window;
                buffer.RemoveRange(0, drop);
                rawBuffer.RemoveRange(0, drop);
            }

            // 3. TRAIN (warm-start the live candidate; budget tied to fresh data, sampled from the full buffer)
            events.Stage?.Invoke("training");
            var pool = buffer.ToArray();
            long budget = (long)fresh.Length * cfg.ReusePerNewSample;
            var trainClock = Stopwatch.StartNew();
            double mse = trainer.RunSamples(pool, budget, cfg.Cores, ct);
            trainer.FoldVirtualIntoL0();   // consolidate this pass's king-independent virtual weights into L0
            trainClock.Stop();

            // 4. CHECKPOINT (latest live net + state + best; replay buffer every MeasureEvery gens)
            events.Stage?.Invoke("saving");
            Save();

            // 5. MEASURE + GATE
            double? score = null;
            if (generation % cfg.MeasureEvery == 0 && !ct.IsCancellationRequested)
            {
                events.Stage?.Invoke("measuring");
                if (!netTeacher)
                {
                    score = Match(trainer.Net, null, ct);                 // candidate vs hand-crafted anchor
                    if (score >= cfg.SwitchThreshold)
                    {
                        netTeacher = true;
                        bestNet = trainer.Net.Clone();
                        bestScore = score.Value;
                        events.Info?.Invoke($"net surpassed hand-crafted ({score:P0}) → net teacher + gating on");
                        Save(); SaveBest();
                    }
                }
                else
                {
                    // Net-vs-net gate: only promote the candidate (and regenerate against it) if it actually
                    // beats the reigning best head-to-head. This ratchets, so a candidate that drifts down
                    // can't demote the best or poison the self-play data.
                    double gate = Match(trainer.Net, bestNet, ct);
                    score = Match(trainer.Net, null, ct);                 // vs anchor, for the progress curve
                    if (gate >= cfg.GateThreshold)
                    {
                        bestNet = trainer.Net.Clone();
                        bestScore = score ?? bestScore;
                        events.Info?.Invoke($"candidate beat best ({gate:P0} h2h, {score:P0} vs anchor) → promoted");
                        SaveBest();
                    }
                    else
                    {
                        events.Info?.Invoke($"candidate held below best ({gate:P0} h2h) → best kept");
                    }
                }
            }

            events.Iteration?.Invoke(new IterReport(
                generation, buffer.Count, netTeacher,
                genClock.Elapsed.TotalSeconds, cfg.GamesPerIter / Math.Max(0.001, genClock.Elapsed.TotalSeconds),
                trainClock.Elapsed.TotalSeconds, mse, score));
        }
        Save();
        SaveCorpus();   // capture the final buffer so the next run resumes with it
    }

    /// <summary>Head-to-head match: <paramref name="a"/> vs <paramref name="b"/> (null = hand-crafted eval),
    /// alternating colours. Returns a's score in [0,1].</summary>
    private double Match(NnueNetwork? a, NnueNetwork? b, CancellationToken ct)
    {
        var rng = new Random(777);
        int w = 0, d = 0, l = 0;
        for (int g = 0; g < cfg.MeasureGames && !ct.IsCancellationRequested; g++)
        {
            var sa = new Searcher(16) { Quiet = true }; if (a != null) sa.SetNnue(a);
            var sb = new Searcher(16) { Quiet = true }; if (b != null) sb.SetNnue(b);
            bool aWhite = (g & 1) == 0;
            var r = GameRunner.PlayGame(aWhite ? sa : sb, aWhite ? sb : sa, cfg.Depth, rng, cfg.RandomPlies);
            if (r == GameRunner.Result.Draw) d++;
            else if ((r == GameRunner.Result.WhiteWins) == aWhite) w++;
            else l++;
            events.Progress?.Invoke(g + 1, cfg.MeasureGames);
        }
        int played = w + d + l;
        return played > 0 ? (w + 0.5 * d) / played : 0;
    }

    // ---- persistence ----

    private string LatestPath => Path.Combine(netDir, "latest.nnue");   // live candidate (warm-start resume)
    private string BestPath => Path.Combine(netDir, "best.nnue");      // released / teacher net (ratchets up)
    private string StatePath => Path.Combine(netDir, "state.txt");
    private string CorpusPath => Path.Combine(netDir, "corpus.trd");    // persisted replay buffer

    private void Save()
    {
        trainer.Net.Save(LatestPath);
        System.IO.File.WriteAllText(StatePath, $"{generation} {(netTeacher ? 1 : 0)} {bestScore:F4}");
        if (generation % cfg.MeasureEvery == 0)
        {
            trainer.Net.Save(Path.Combine(netDir, $"gen_{generation:D4}.nnue"));   // periodic history checkpoint
            SaveBest();
            SaveCorpus();
        }
    }

    private void SaveBest() => bestNet.Save(BestPath);

    /// <summary>
    /// Persist the replay buffer atomically (temp file + rename) so a crash mid-write can't corrupt it.
    /// </summary>
    private void SaveCorpus()
    {
        if (rawBuffer.Count == 0) return;
        string tmp = CorpusPath + ".tmp";
        using (var wr = new TrainingData.Writer(tmp))
            foreach (var s in rawBuffer) wr.Add(s.Fen, s.ScoreCp, s.Result);
        if (System.IO.File.Exists(CorpusPath)) System.IO.File.Delete(CorpusPath);
        System.IO.File.Move(tmp, CorpusPath);
    }

    private void LoadCorpus()
    {
        if (!System.IO.File.Exists(CorpusPath)) return;
        try
        {
            var samples = TrainingData.Read(CorpusPath);
            if (samples.Count > cfg.Window) samples.RemoveRange(0, samples.Count - cfg.Window);
            rawBuffer.AddRange(samples);
            buffer.AddRange(Trainer.BuildExamples(samples, cfg.Lambda));
        }
        catch { /* corrupt/old corpus → start with an empty buffer, it refills */ }
    }

    private static NnueNetwork? TryLoad(string path)
    {
        try { return System.IO.File.Exists(path) ? NnueNetwork.Load(path) : null; }
        catch { return null; }
    }

    private NnueNetwork? TryResume(out int gen, out bool teacher, out double best)
    {
        gen = 0; teacher = false; best = 0;
        if (!System.IO.File.Exists(LatestPath) || !System.IO.File.Exists(StatePath)) return null;
        var parts = System.IO.File.ReadAllText(StatePath).Split(' ', StringSplitOptions.RemoveEmptyEntries);
        if (parts.Length >= 1) _ = int.TryParse(parts[0], out gen);
        if (parts.Length >= 2) teacher = parts[1] == "1";
        if (parts.Length >= 3) double.TryParse(parts[2], System.Globalization.CultureInfo.InvariantCulture, out best);
        try { return NnueNetwork.Load(LatestPath); }
        catch { gen = 0; teacher = false; best = 0; return null; }
    }
}
